language: python
python:
  - "2.7"
before_install:
  # Download bundle of python eggs, and use it as download cache
  - "wget http://depot.makina-corpus.org/public/geotrek/geotrek-bundle.tar.gz -O /tmp/geotrek-bundle.tar.gz || true"
  - "tar -zxf /tmp/geotrek-bundle.tar.gz --directory=$HOME || mkdir -p $HOME/.buildout/downloads"
  - echo -e "[buildout]\ndownload-cache=$HOME/.buildout/downloads" > $HOME/.buildout/default.cfg
install:
  - deactivate
  - ./install.sh --tests
script:
  - make env_test test
  - make test_js
  # Re-run for coverage
  - rm -rf ./var/media/maps/*
  - ./bin/coverage run ./bin/django test geotrek
after_success:
  # Report coverage results to coveralls.io
  - ./bin/coverage report -m
  - pip install coveralls
  - coveralls
notifications:
  email: false
  irc: "irc.freenode.org#geotrek"
